# Generated by Django 4.2.7 on 2024-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
