# Generated by Django 4.2.7 on 2024-02-16 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_blog_is_active_portfolio_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Ceertificates",
            },
        ),
    ]
